### ISSUE TITLE
Automatically register Sample Data file once placed in S3

### ISSUE THREAD

**Issue by nateiam** [FINRAOS/herd#232]
As a Business Metadata Analyst I want Sample Data files that I place in S3 to be associated with the BDef as soon as the upload is complete.

Pre-requisite - the user previously called #226  "Obtain information required to upload Sample Data" and has initiated the upload operation to the location provided.

Acceptance Criteria
* Upon completion of upload, file uploaded is associated with the BDef as a Sample Data file
* S3 prefix and file name is available via BDef Descriptive Info endpoint as described in #207  
* TECH NOTE - this will likely occur via S3 notification and might need a new queue

**Comment by zubair-nbx** [comment]
Thanks @nateiam , for writing that detailed tutorial about how to do this. I following your tutorial about uploading Sample-Data: https://github.com/FINRAOS/herd/wiki/Publishing-Sample-Data 

Here is a quick question: 
- How would Herd get notified of the new object in S3 bucket, the call  https://your-herd-hostname/herd-app/docs/rest/index.html#!/Upload_and_Download/UploadandDownload_initiateDownloadSingleSampleFile doesn't creates entry in any of 'ntfcn_*' tables. 

- Is there some configuration needs to be done on AWS to send notifications in S3 ?
- Which service creates the notification ? I assume JMS Listens to notifications in Herd, however there are cron jobs configured in 'qrtz_cron_triggers' table.

**Comment by zubair-nbx** [comment]
Thanks @nateiam , that's Great. It make that feature work. If you like you can close that ticket too.

**Comment by zubair-nbx** [comment]
Seems we can add one more point to tutorial, By default SQS doesn't allow S3 to write notifications to it: 

- Select the relevant SQS queue. 
- Select Permissions Tab and click 'EditPolicyDocument' then add the following policy: 

> {
  "Version": "2008-10-17",
  "Id": "arn:aws:sqs:us-east-1:xxxxxxxxxx:s3_managed_sample_data_queue/s3-to-sqs",
  "Statement": [
    {
      "Sid": "herd-s3-to-sqs",
      "Effect": "Allow",
      "Principal": {
        "AWS": " * "
      },
      "Action": "SQS:SendMessage",
      "Resource": "arn:aws:sqs:us-east-1:xxxxxxxxxx:s3_managed_sample_data_queue",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:s3-managed-sample-data"
        }
      }
    }
  ]
}

**Comment by nateiam** [comment]
Thanks again @zubair-nbx, I updated the tutorial to reference this. 

Very glad the sample data feature works for you now. I am fully confident that our software works and it is well tested. We would both agree our documentation needs improvement. But this was a great collaboration that resulted in good documentation. Don't hesitate to ask more questions or make more suggestions.

**Comment by zubair-nbx** [comment]
Welcome @nateiam , Its good software that you and your team has written, specially in terms of quality and code coverage. I feel it like 'kernel' for data lineage and catalog. It provides necessary API to execute tasks but by itself it does perform these. 

Why is the Herd-UI read-only? I mean Business-Object definitions can be created from UI. What I am thinking is developing a layer between Herd-Server and Herd-UI which acts like wizards to do these tasks.  

- Also if we can submit tasks via EMR API, what exactly the Jobs_API does, I assume it automates API call via workflows. 
- SQS quues, what is the purpose of ([Configuration Values page is missing these](https://github.com/FINRAOS/herd/wiki/configuration-values)): 
--- herd.notifications.sqs.incoming.queue.name
--- herd.notifications.sqs.outgoing.queue.name
- Is it possible that if I attache BusinessObjectData files already and later want the EMR step of use these files and not providing source files explicitly ?

About Tutorials: 
My two cents about it, there should be 4-5 tutorials series as follow: 
1- [Registering Business Objects in Herd. ](https://github.com/FINRAOS/herd/wiki/quick-start-to-registering-data).
2- [Uploading and Registering data via uploader tool](https://github.com/FINRAOS/herd/wiki/uploader-users-guide). (Optional to follow)
2- [Publish Sample Data. ](https://github.com/FINRAOS/herd/wiki/Publishing-Sample-Data)
3- EMR step to partition data based on a partition key. 
4- Create DataLineage on Format level and BO level. (I will do it and send you for review and posting.)
5- Configure LDAP and allow specific user to access a particular set of data. 
Advance Tutorial: 
6- Automating tasking using jobs_api and activiti workflows. 

and Finally may be we can create a FAQ section to post important questions. 
In that order one can explore all major features of Herd and here is [Tutorial to Deploy Herd Locally.](https://docs.google.com/document/d/1kLQeRnBMRRDZajYOwupnfsL2AP_d4Ew6mIiWq7Y_vNI/edit?usp=sharing)

**Comment by aniruddhadas9** [comment]
@zubair-nbx, I would say Herd-UI have edit capability in some pages but these are restricted to security function and namespace authorization. Users can edit/update data if they have proper security function and namespace level permission. In this image you can see user can edit many section of the page if they permitted to do that. Also data object list link is only visible to permitted user int he shreenshot. 

![herd-ui-edit-data](https://user-images.githubusercontent.com/1029809/38430276-d1ccf6e0-398e-11e8-8e16-5e42ca875229.png)

**Comment by zubair-nbx** [comment]
Yes, you are correct @aniruddhadas9 , I was pointing toward BusinessObjectDefinations, Formats, Data, Tags, Categories creation etc. Which don't interact with EMR stuff.

**Comment by nateiam** [comment]
Hi @zubair-nbx 

> Also if we can submit tasks via EMR API, what exactly the Jobs_API does, I assume it automates API call via workflows.

You are correct. The Jobs API is to define and execute workflows around interactions with Herd. The Activiti BPMN engine is a third-party open source tool that we package in Herd as the runtime for these workflows. We have also created a number of [Activiti tasks](https://github.com/FINRAOS/herd/wiki/activiti-task-toc) that make it very easy to interact with Herd from within the Activit workflows.

So you can use EMR (either directly or through Herd pass-through APIs) for heavy lifting and manipulating the data. And use Jobs (Activiti) for orchestrating workflows that can include Herd interaction and EMR interaction.

> Is it possible that if I attach BusinessObjectData files already and later want the EMR step to use these files and not providing source files explicitly ?

I am not certain if I understand the question. But it is possible to do something like:

* Register a BusinessObjectData (BData for short) that includes some files
* Later, from an EMR instance or a Job, call Herd to obtain information about that BData in various ways:
  * Use [BData Get](https://finraos.github.io/herd/docs/latest/rest/index.html#!/Business_Object_Data/BusinessObjectData_getBusinessObjectData) to get everything about that specific BData (including references to the files and the bucket and prefix)
* User [BData Generate DDL](https://finraos.github.io/herd/docs/latest/rest/index.html#!/Business_Object_Data/BusinessObjectData_generateBusinessObjectDataDdl) to obtain Hive-ready DDL that you can execute on EMR to create an external table pointing to the files from a single BData or a range of BData

In particular the Generate DDL use case is very powerful, it deserves a tutorial of it's own. Let me know if you have in interest in this and maybe we can collaborate to make a tutorial!
