### ISSUE TITLE
UI - 403 on local machine

### ISSUE THREAD

**Issue by tinshuksingh** [FINRAOS/herd#364]
I am trying to setup herd on my local machine (Windows), did all required resources setup which allowed me to access HerdRestAPI, but UI fails to load with 403 error code:

![herd_403](https://user-images.githubusercontent.com/20110386/35394684-5f8f70f6-020e-11e8-8a7f-47fa457028b6.PNG)

**Comment by tinshuksingh** [comment]
I could resolve the 403 error, but seems like herd doesn't provides any UI for the REST API's, can someone confirm if there is any inbuild UI accommodating the REST API's? I could not find required css and js file in the war file.
![herd_404](https://user-images.githubusercontent.com/20110386/35519802-44521f5c-053b-11e8-847f-25be469e5ed6.PNG)

**Comment by nateiam** [comment]
Addressed in #360
