### ISSUE TITLE
Herd architecture and documentation

### ISSUE THREAD

**Issue by tinshuksingh** [FINRAOS/herd#369]
Hi Team,

We configured the herd application and herd-ui successfully on ec2 instance without the CloudFormation script you provided. 
We went through [wiki](https://github.com/FINRAOS/herd/wiki) and got to know some basics of herd. Now we wanted to understand all the herd components thoroughly. 

Could you please provide us an **architecture** of herd and any **detailed document** if you have?

Thanks,
Tinshuk Banafar

**Comment by nateiam** [comment]
Wow Tinshuk, that is great news! Glad you were able to take it apart and put it back together again without the CloudFormation template, that is impressive.

The wiki is a good place to start. We also have more documentation on certain features. The documentation was developed here at FINRA and we need to take some effort to scrub it of any proprietary information before putting it on the GitHub wiki. So unfortunately I can't just put everything out here. But we are very dedicated to this open source effort and we want to be good citizens on GitHub and we are ready to put in the effort to add to our documentation. 

I propose that we arrange some time soon to talk. I would like to cover Herd at a high level learn about your areas of interest. We can discuss your needs and fill in any gaps in our conversation. Then following the meeting we can focus on certain areas of the documentation that will be high-value to you and the open source community.

Please contact us on herd@finra.org to coordinate a good time or to discuss further.

**Comment by nateiam** [comment]
Hey that is great! To me that looks like a good start at the software architecture of Herd. I am going to ask our tech lead and architect to provide some comments. 

@afelde @foxsmart -- guys take a look at this!

Thanks @zubair-nbx that is an excellent contribution.

**Comment by foxsmart** [comment]
Thanks for providing an initial architecture diagram @zubair-nbx!

Herd sends outbound SQS messages to communicate "Business Object Data" status changes which would fit better than "New Business Object Definitions". There are also the following other salient tiers that we might want to add to the diagram at some point:

- herd-app: application code and configuration needed to build and initializes the WAR. The WAR itself is built as part of herd-war. This tier is the highest level tier and depends on all other tiers beneath it. 
- herd-core: low level code that can be used by all upper tiers except herd-model and herd-model-api
- herd-model-api: external dependencies (i.e. DTO's) for other systems to use when they want to invoke herd REST API's.

**Comment by nateiam** [comment]
@zubair-nbx, glad your RnD continues, I can see you are gaining deep knowledge through research and experimentation. 

I agree there should be more tutorials. As of now we are creating them as requirements demand. For example last week we created [Populating Business Metadata](https://github.com/FINRAOS/herd/wiki/Populating-Business-Metadata) and today I just created another for [Publishing Sample Data](https://github.com/FINRAOS/herd/wiki/Publishing-Sample-Data) in response to your question. We also hope to soon dedicate some effort to creating more tutorials for basic items like Jobs, EMR, Lineage, etc.

Answers to your questions:
 

> Activiti workflows is a way to simplify EMR cluster creation, management and to run jobs, workflows are not used to automate users Business Rules or to build data lake in Herd. Right ?

Activiti workflows are intended to allow users to easily automate repetitive interactions with Herd. These are written in a declarative fashion with industry-standard BPMN XML that allows for orchestration of tasks. We have created [Activti wrapper tasks](https://github.com/FINRAOS/herd/wiki/activiti-task-toc) for several common interactions with Herd.

A simplified example workflow could be:

1. Use [Generate DDL](https://github.com/FINRAOS/herd/wiki/generate-business-object-data-ddl) to obtain DDL for some source data
1. Use [Create EMR Cluster](https://github.com/FINRAOS/herd/wiki/create-emr-cluster) and [Add Hive Step](https://github.com/FINRAOS/herd/wiki/emr-add-hive-step) to transform the source data into another format and write it to an external table in S3
1. Use [Register Business Object Data](https://github.com/FINRAOS/herd/wiki/register-business-object-data) to register the new data in Herd
1. And frequently teams have additional workflow logic in Activiti to handle conditionals, loops, retry, etc. or some lightweight logic in Activiti JavaScript tasks.

You are correct that Activiti workflows are not intended to perform data processing directly in the Activiti runtime -- they are intended only for workflow and orchestration of data processing steps in other runtime platforms such as EMR.

> Data-Lineage: Does EMR steps provide a way to automatically create lineage, it mean if a BussinessObject(csv file) is transformed by a EMR using Herd and there is a resulting file with modified columns, Can Herd create a lineage for it ? How / where Herd keeps track of Actions performed on files and who performed ?

Herd does not include a mechanism to automatically create lineage with EMR. Instead we rely on explicit registration of lineage when data is registered. This allows Herd to be totally agnostic of the platforms and engines used for data processing. 

Note that some teams at FINRA have created frameworks that simplify data processing on EMR and registration with Herd -- and these frameworks commonly handle registration of lineage without additional work by users.

Detailed lineage is included in the https://_your-herd-hostname_/herd-app/docs/rest/index.html#!/Business_Object_Data/BusinessObjectData_createBusinessObjectData endpoint. Users registering data can pass references to a collection of BusinessObjectDataParents that were used in creation of the Business Object Data they are registering. The parent and child references are then visible in UDC (on the Data Object Details page) and present in the Business Object Data GET endpoint response. This level of lineage is useful for detailed analysis and troubleshooting -- exactly which partitions and/or files came from which.

Lineage is also expressed at a higher level in the model -- at the Format level. This lineage is independent and need only be created once per Format by calling https://_your-herd-hostname_/herd-app/docs/rest/index.html#!/Business_Object_Format/BusinessObjectFormat_updateBusinessObjectFormatParents. This higher-level lineage is useful for visualizing data flow between Formats with the 'Lineage' button on the Data Entity page in the UDC.

> Any User either System User or Subject Matter Expert should come to Herd via LDAP integration, Right ? There is no other mechanism to add users / contacts at the time. Herd by itself doesn't provide user registration.

Correct, Herd has no concept of users outside that introduced by LDAP integration for authentication, authorization, and lookup of contact information of SMEs.

> And last, how can I upload the sampleDataFile for DataEntity so that I can see the "Sample Data" button enabled on Herd-UI (see img below)

See new tutorial [Publishing Sample Data](https://github.com/FINRAOS/herd/wiki/Publishing-Sample-Data) and open a new issue if you have questions. And don't worry, not all Herd features are this complex to configure!
