### ISSUE TITLE
Stack Creation Fails for herd-mdl

### ISSUE THREAD

**Issue by stevejhall** [FINRAOS/herd#394]
Following the information at https://finraos.github.io/herd-mdl/docs.html and follow the instructions in the Basic Install section. 

The file installMDL.yml file is downloaded as the starting point
That file is then uploaded to CloudFormation to start the deployment
That deployment downloads a zip from GitHub
The Zip is herd-mdl-v1.3.0 from https://github.com/FINRAOS/herd-mdl/releases

At line 391 it appears that we delegate to a child template that was within the zip:  '/cft/mdl.yml'
In lines 392 through 428 we pass parameters to the child template. 
The parameters of interest are not defined in the installMDL.yml file, and they are not passed to the child.

The child defines the values, but has no default setting.
Accordingly, the script fails with errors as follows:

Parameters: [CloudWatchRetentionDays, PrestoMaxMemoryPerNode] must have values

I can get around this error by making changes to the template.

CloudWatchRetentionDays:
    Description: 'Retention days for CloudWatch logs'
    Type: Number
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 90
PrestoMaxMemoryPerNode:
    Description: query.max-memory-per-node parameter for Presto
    Type: String
    Default: 3G

and passing them to the child template by adding the following lines at 438 and 439:
CloudWatchRetentionDays: !Ref CloudWatchRetentionDays
PrestoMaxMemoryPerNode: !Ref PrestoMaxMemoryPerNode

**Comment by kusid** [comment]
Hello @stevejhall !
Thank you for your interest in herd-mdl. You are absolutely correct - we have a parent 'wrapper' template (installMDL.yml) which downloads our release artefacts and proceeds with the installation of all the components of herd-mdl as nested stacks. I went over your issue and I'm guessing that you might have tried to install release 1.3.0 from an older `installMDL.yml` wrapper template which does not have the parameters you mention. I've updated our documentation at herd-mdl's [basic-install](https://finraos.github.io/herd-mdl/docs/basic-install/) section to be more clearer and point to the latest release-artefact. Please give it another try and let us know if you need any further assistance. Have a nice day!

**Comment by stevejhall** [comment]
Thank you.  I have this working now.
