### ISSUE TITLE
Demo Install Cloudformation Template 0.83.0 Failed - 16K UserData Limit

### ISSUE THREAD

**Issue by grokspeed** [FINRAOS/herd#412]
The initialization script failed as it exceeds the 16K UserData limit on EC2. 

Please help.

**Comment by stevejhall** [comment]
This question has been answered...

EC2 User Data Limit Exceeded
#393 opened 29 days ago by stevejhall 

Per the sugggestion, I have moved to Herd-Mdl  That stack sets up in about 2 hours via a Cloud Formation Script.

**Comment by nateiam** [comment]
Yes, thanks @stevejhall!
@grokspeed please check out Herd-MDL at https://finraos.github.io/herd-mdl/docs.html and follow the instructions in the Basic Install section -- more details are in the comments to #393 and the Herd-MDL docs.

Also we have a backlog item that I am certain we will soon complete that will fix the Herd docs. We're just figuring out if we should copy or reference the new Herd-MDL install. Any votes from the community??
